name: CI

on:
  push:
    branches: [master, beta]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test
      - name: edit coverage report # hack to support the different paths, since istanbul won't change it
        run: sed -i "s|SF:/.*/src/|SF:/github/workspace/src/|g" coverage/lcov.info
      - name: sonarcloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release:
    name: Building and releasing project
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - name: build
        run: |
          yarn build:ts
          cp package.json dist/package.json
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist
          yarn --frozen-lockfile
          yarn semantic-release
